const base = {
  'nav.home': 'Home', 'nav.about': 'More Than About', 'nav.committees': 'Committees', 'nav.location': 'Location', 'nav.program': 'Program', 'nav.accommodation': 'Accommodation', 'nav.roundTable': 'Round Table', 'nav.testimonials': 'Testimonials', 'nav.awards': 'Awards', 'nav.howTo': 'How To', 'nav.news': 'News', 'nav.sponsors': 'Sponsors', 'nav.gallery': 'Gallery', 'nav.contact': 'Contact',
  'hero.overline': '9-10 October 2026 · Timișoara', 'hero.title': 'Traian Vuia 2026 International Invention and Innovation Salon', 'hero.title.line1': 'International Salon of', 'hero.title.line2.prefix': 'Inventions and Innovation', 'hero.title.line2.em': 'Traian Vuia', 'hero.title.line2.suffix': '2026', 'hero.subtitle': 'The first flight of ideas shaping the future.', 'hero.ctaRegister': 'Register', 'hero.ctaLearn': 'Learn more',
  'countdown.days': 'Days', 'countdown.hours': 'Hours', 'countdown.minutes': 'Minutes', 'countdown.seconds': 'Seconds',
  'sections.about.title': 'More Than About', 'sections.about.text': 'History, mission and vision for an international innovation salon.', 'sections.about.history': 'History', 'sections.about.historyText': 'Salon history placeholder.', 'sections.about.mission': 'Mission', 'sections.about.missionText': 'Mission and vision placeholder.', 'sections.about.organizers': 'Organizers', 'sections.about.organizersText': 'Organizer logos placeholder.',
  'stats.editions': 'Editions', 'stats.countries': 'Countries', 'stats.inventions': 'Inventions', 'stats.awards': 'Awards',
  'sections.committees.title': 'Committees', 'placeholder.member': 'Member name', 'placeholder.role': 'Title · Institution',
  'sections.location.title': 'Location', 'sections.location.place': 'Regional Business Center Timișoara', 'sections.location.address': '22 Eroilor de la Tisa Blvd, Timișoara', 'sections.location.directions': 'Directions and access placeholder.',
  'sections.program.title': 'Program', 'sections.program.day1': 'Day 1 · 9 October', 'sections.program.day1Items': 'Arrival, Registration, Opening Ceremony, Exhibition, Evaluation, Networking', 'sections.program.day2': 'Day 2 · 10 October', 'sections.program.day2Items': 'Exhibition for visitors, Round Table, Awards Gala',
  'sections.accommodation.title': 'Accommodation', 'sections.accommodation.placeholder': '★★★★★ · Address · Price range',
  'sections.roundTable.title': 'Round Table', 'sections.roundTable.text': 'Discussion topics and international speakers (placeholder).', 'sections.roundTable.topic1': 'Technology transfer', 'sections.roundTable.topic2': 'Startup & research', 'sections.roundTable.topic3': 'Sustainable innovation',
  'sections.testimonials.title': 'Testimonials', 'sections.testimonials.t1': '"An exceptional event for inventors."', 'sections.testimonials.t2': '"International-level networking."', 'sections.testimonials.t3': '"Relevant awards and flawless organization."',
  'sections.awards.title': 'Awards', 'awards.a1': 'International Invention Award', 'awards.a2': 'Romanian Invention Award', 'awards.a3': 'Young Inventor Award', 'awards.a4': 'Woman Inventor Award', 'awards.a5': 'Best Design Award', 'awards.a6': 'Special Awards', 'awards.a7': 'Grand Prize of the Exhibition',
  'sections.howTo.title': 'How To Participate', 'sections.howTo.step1': 'Complete the registration form.', 'sections.howTo.step2': 'Send the poster according to guidelines.', 'sections.howTo.step3': 'Participation fee: 500 RON / 100 EUR per invention.', 'sections.howTo.step4': 'Receive confirmation and bank details (placeholder).', 'sections.howTo.catalog': 'Download catalog (placeholder)',
  'sections.news.title': 'News', 'sections.news.n1': 'Registration opening announced', 'sections.news.n2': 'New international partnerships', 'sections.news.n3': 'Preliminary agenda published', 'placeholder.news': 'Article placeholder.',
  'sections.sponsors.title': 'Sponsors', 'sections.sponsors.partners': 'Partners', 'sections.sponsors.cta': 'Become a sponsor', 'placeholder.logo': 'Logo placeholder',
  'sections.gallery.title': 'Gallery', 'sections.gallery.video': 'Video gallery section (placeholder).',
  'sections.contact.title': 'Contact', 'sections.contact.org': 'Organizer: University of Life Sciences "King Mihai I" Timișoara',
  'form.name': 'Name', 'form.email': 'Email', 'form.subject': 'Subject', 'form.message': 'Message', 'form.send': 'Send',
  'footer.quick': 'Quick links', 'footer.social': 'Social media'
};

const mk = (o) => ({ ...base, ...o });

window.translations = {
  ro: mk({
    'nav.home': 'Acasă', 'nav.committees': 'Comitete', 'nav.location': 'Locație', 'nav.accommodation': 'Cazare', 'nav.roundTable': 'Masa rotundă', 'nav.testimonials': 'Testimoniale', 'nav.awards': 'Premii', 'nav.howTo': 'Cum participi', 'nav.news': 'Noutăți', 'nav.sponsors': 'Sponsori', 'nav.gallery': 'Galerie',
    'hero.overline': '9-10 Octombrie 2026 · Timișoara', 'hero.title': 'Salonul Internațional de Invenții și Inovație Traian Vuia 2026', 'hero.title.line1': 'Salonul Internațional de', 'hero.title.line2.prefix': 'Invenții și Inovație', 'hero.title.line2.em': 'Traian Vuia', 'hero.title.line2.suffix': '2026', 'hero.subtitle': 'Primul zbor al ideilor care schimbă viitorul.', 'hero.ctaRegister': 'Înregistrează-te', 'hero.ctaLearn': 'Află mai mult',
    'countdown.days': 'Zile', 'countdown.hours': 'Ore', 'countdown.minutes': 'Minute', 'countdown.seconds': 'Secunde',
    'sections.about.text': 'Istorie, misiune și viziune pentru un salon internațional dedicat inovației.', 'sections.about.history': 'Istorie', 'sections.about.historyText': 'Placeholder istorie salon.', 'sections.about.mission': 'Misiune', 'sections.about.missionText': 'Placeholder misiune și viziune.', 'sections.about.organizers': 'Organizatori', 'sections.about.organizersText': 'Placeholder logo-uri organizatori.',
    'stats.editions': 'Ediții', 'stats.countries': 'Țări', 'stats.inventions': 'Invenții', 'stats.awards': 'Premii',
    'sections.committees.title': 'Comitete', 'placeholder.member': 'Nume membru', 'placeholder.role': 'Titlu · Instituție',
    'sections.location.title': 'Locație', 'sections.location.place': 'Centrul Regional de Afaceri Timișoara', 'sections.location.address': 'Bulevardul Eroilor de la Tisa 22, Timișoara', 'sections.location.directions': 'Placeholder direcții și acces.',
    'sections.program.day1': 'Ziua 1 · 9 Octombrie', 'sections.program.day1Items': 'Sosire, Înregistrare, Deschidere, Expoziție, Evaluare, Networking', 'sections.program.day2': 'Ziua 2 · 10 Octombrie', 'sections.program.day2Items': 'Expoziție publică, Masă rotundă, Gala premiilor',
    'sections.accommodation.title': 'Cazare', 'sections.accommodation.placeholder': '★★★★★ · Adresă · Interval preț',
    'sections.roundTable.title': 'Masa rotundă', 'sections.roundTable.text': 'Teme de discuție și speakeri internaționali (placeholder).', 'sections.roundTable.topic1': 'Transfer tehnologic', 'sections.roundTable.topic2': 'Startup & cercetare', 'sections.roundTable.topic3': 'Inovație sustenabilă',
    'sections.testimonials.title': 'Testimoniale', 'sections.testimonials.t1': '„Un eveniment excepțional pentru inventatori.”', 'sections.testimonials.t2': '„Networking de nivel internațional.”', 'sections.testimonials.t3': '„Premii relevante și organizare impecabilă.”',
    'sections.awards.title': 'Premii', 'awards.a1': 'Premiul Internațional pentru Invenție', 'awards.a2': 'Premiul Român pentru Invenție', 'awards.a3': 'Premiul Tânărului Inventator', 'awards.a4': 'Premiul Femeii Inventator', 'awards.a5': 'Premiul pentru Design', 'awards.a6': 'Premii Speciale', 'awards.a7': 'Marele Premiu al Expoziției',
    'sections.howTo.title': 'Cum participi', 'sections.howTo.step1': 'Completezi formularul de înscriere.', 'sections.howTo.step2': 'Trimiți posterul conform ghidului.', 'sections.howTo.step3': 'Taxa: 500 RON / 100 EUR per invenție.', 'sections.howTo.step4': 'Primești confirmare și detalii bancare (placeholder).', 'sections.howTo.catalog': 'Descarcă catalog (placeholder)',
    'sections.news.title': 'Noutăți', 'sections.news.n1': 'Anunț deschidere înscrieri', 'sections.news.n2': 'Parteneriate internaționale noi', 'sections.news.n3': 'Program preliminar publicat', 'placeholder.news': 'Placeholder articol.',
    'sections.sponsors.title': 'Sponsori', 'sections.sponsors.partners': 'Parteneri', 'sections.sponsors.cta': 'Devino sponsor',
    'sections.gallery.title': 'Galerie', 'sections.gallery.video': 'Secțiune galerie video (placeholder).',
    'sections.contact.org': 'Organizator: Universitatea de Științele Vieții "Regele Mihai I" Timișoara',
    'form.name': 'Nume', 'form.subject': 'Subiect', 'form.message': 'Mesaj', 'form.send': 'Trimite',
    'footer.quick': 'Linkuri rapide'
  }),
  en: base,
  fr: mk({ 'nav.home': 'Accueil', 'nav.committees': 'Comités', 'nav.location': 'Lieu', 'nav.accommodation': 'Hébergement', 'nav.roundTable': 'Table ronde', 'nav.testimonials': 'Témoignages', 'nav.awards': 'Prix', 'nav.howTo': 'Comment participer', 'nav.news': 'Actualités', 'nav.gallery': 'Galerie', 'hero.ctaRegister': 'Inscrivez-vous', 'hero.ctaLearn': 'En savoir plus', 'countdown.days': 'Jours', 'countdown.hours': 'Heures', 'countdown.minutes': 'Minutes', 'countdown.seconds': 'Secondes', 'sections.about.title': 'Plus que À propos', 'sections.committees.title': 'Comités', 'sections.location.title': 'Lieu', 'sections.program.title': 'Programme', 'sections.accommodation.title': 'Hébergement', 'sections.roundTable.title': 'Table ronde', 'sections.testimonials.title': 'Témoignages', 'sections.awards.title': 'Prix', 'sections.howTo.title': 'Comment participer', 'sections.news.title': 'Actualités', 'sections.sponsors.title': 'Sponsors', 'sections.gallery.title': 'Galerie', 'sections.contact.title': 'Contact', 'placeholder.member': 'Nom membre', 'placeholder.role': 'Titre · Institution', 'placeholder.news': 'Article provisoire.', 'placeholder.logo': 'Logo provisoire' }),
  de: mk({ 'nav.home': 'Startseite', 'nav.committees': 'Komitees', 'nav.location': 'Ort', 'nav.program': 'Programm', 'nav.accommodation': 'Unterkunft', 'nav.roundTable': 'Runder Tisch', 'nav.testimonials': 'Referenzen', 'nav.awards': 'Preise', 'nav.howTo': 'Teilnahme', 'nav.news': 'Neuigkeiten', 'nav.contact': 'Kontakt', 'hero.ctaRegister': 'Registrieren', 'hero.ctaLearn': 'Mehr erfahren', 'countdown.days': 'Tage', 'countdown.hours': 'Stunden', 'countdown.minutes': 'Minuten', 'countdown.seconds': 'Sekunden', 'sections.about.title': 'Mehr als Über uns', 'sections.committees.title': 'Komitees', 'sections.location.title': 'Ort', 'sections.program.title': 'Programm', 'sections.accommodation.title': 'Unterkunft', 'sections.roundTable.title': 'Runder Tisch', 'sections.testimonials.title': 'Referenzen', 'sections.awards.title': 'Preise', 'sections.howTo.title': 'Teilnahme', 'sections.news.title': 'Neuigkeiten', 'sections.sponsors.title': 'Sponsoren', 'sections.gallery.title': 'Galerie', 'sections.contact.title': 'Kontakt', 'placeholder.member': 'Mitglied', 'placeholder.role': 'Titel · Institution', 'placeholder.news': 'Artikel-Platzhalter.', 'placeholder.logo': 'Logo-Platzhalter' }),
  es: mk({ 'nav.home': 'Inicio', 'nav.committees': 'Comités', 'nav.location': 'Ubicación', 'nav.accommodation': 'Alojamiento', 'nav.roundTable': 'Mesa redonda', 'nav.testimonials': 'Testimonios', 'nav.awards': 'Premios', 'nav.howTo': 'Cómo participar', 'nav.news': 'Noticias', 'nav.sponsors': 'Patrocinadores', 'nav.gallery': 'Galería', 'nav.contact': 'Contacto', 'hero.ctaRegister': 'Regístrate', 'hero.ctaLearn': 'Saber más', 'countdown.days': 'Días', 'countdown.hours': 'Horas', 'countdown.minutes': 'Minutos', 'countdown.seconds': 'Segundos', 'sections.about.title': 'Más que Acerca', 'sections.committees.title': 'Comités', 'sections.location.title': 'Ubicación', 'sections.program.title': 'Programa', 'sections.accommodation.title': 'Alojamiento', 'sections.roundTable.title': 'Mesa redonda', 'sections.testimonials.title': 'Testimonios', 'sections.awards.title': 'Premios', 'sections.howTo.title': 'Cómo participar', 'sections.news.title': 'Noticias', 'sections.sponsors.title': 'Patrocinadores', 'sections.gallery.title': 'Galería', 'sections.contact.title': 'Contacto', 'placeholder.member': 'Nombre miembro', 'placeholder.role': 'Título · Institución', 'placeholder.news': 'Artículo provisional.', 'placeholder.logo': 'Logo provisional' }),
  it: mk({ 'nav.committees': 'Comitati', 'nav.location': 'Luogo', 'nav.program': 'Programma', 'nav.accommodation': 'Alloggio', 'nav.roundTable': 'Tavola rotonda', 'nav.testimonials': 'Testimonianze', 'nav.awards': 'Premi', 'nav.howTo': 'Come partecipare', 'nav.news': 'Notizie', 'nav.contact': 'Contatti', 'hero.ctaRegister': 'Registrati', 'hero.ctaLearn': 'Scopri di più', 'countdown.days': 'Giorni', 'countdown.hours': 'Ore', 'countdown.minutes': 'Minuti', 'countdown.seconds': 'Secondi', 'sections.about.title': 'Più di Chi siamo', 'sections.committees.title': 'Comitati', 'sections.location.title': 'Luogo', 'sections.program.title': 'Programma', 'sections.accommodation.title': 'Alloggio', 'sections.roundTable.title': 'Tavola rotonda', 'sections.testimonials.title': 'Testimonianze', 'sections.awards.title': 'Premi', 'sections.howTo.title': 'Come partecipare', 'sections.news.title': 'Notizie', 'sections.sponsors.title': 'Sponsor', 'sections.gallery.title': 'Galleria', 'sections.contact.title': 'Contatti', 'placeholder.member': 'Nome membro', 'placeholder.role': 'Titolo · Istituzione', 'placeholder.news': 'Articolo provvisorio.', 'placeholder.logo': 'Logo provvisorio' }),
  pt: mk({ 'nav.home': 'Início', 'nav.committees': 'Comitês', 'nav.location': 'Local', 'nav.accommodation': 'Acomodação', 'nav.testimonials': 'Depoimentos', 'nav.awards': 'Prêmios', 'nav.howTo': 'Como participar', 'nav.news': 'Notícias', 'nav.sponsors': 'Patrocinadores', 'nav.contact': 'Contato', 'hero.ctaRegister': 'Inscreva-se', 'hero.ctaLearn': 'Saiba mais', 'countdown.days': 'Dias', 'countdown.hours': 'Horas', 'countdown.minutes': 'Minutos', 'countdown.seconds': 'Segundos', 'sections.about.title': 'Mais que Sobre', 'sections.committees.title': 'Comitês', 'sections.location.title': 'Local', 'sections.program.title': 'Programa', 'sections.accommodation.title': 'Acomodação', 'sections.roundTable.title': 'Mesa redonda', 'sections.testimonials.title': 'Depoimentos', 'sections.awards.title': 'Prêmios', 'sections.howTo.title': 'Como participar', 'sections.news.title': 'Notícias', 'sections.sponsors.title': 'Patrocinadores', 'sections.gallery.title': 'Galeria', 'sections.contact.title': 'Contato', 'placeholder.member': 'Nome membro', 'placeholder.role': 'Título · Instituição', 'placeholder.news': 'Artigo provisório.', 'placeholder.logo': 'Logo provisório' }),
  ru: mk({ 'nav.home': 'Главная', 'nav.committees': 'Комитеты', 'nav.location': 'Локация', 'nav.program': 'Программа', 'nav.accommodation': 'Проживание', 'nav.roundTable': 'Круглый стол', 'nav.testimonials': 'Отзывы', 'nav.awards': 'Награды', 'nav.howTo': 'Как участвовать', 'nav.news': 'Новости', 'nav.sponsors': 'Спонсоры', 'nav.gallery': 'Галерея', 'nav.contact': 'Контакты', 'hero.ctaRegister': 'Зарегистрироваться', 'hero.ctaLearn': 'Подробнее', 'countdown.days': 'Дни', 'countdown.hours': 'Часы', 'countdown.minutes': 'Минуты', 'countdown.seconds': 'Секунды', 'sections.about.title': 'Больше чем О нас', 'sections.committees.title': 'Комитеты', 'sections.location.title': 'Локация', 'sections.program.title': 'Программа', 'sections.accommodation.title': 'Проживание', 'sections.roundTable.title': 'Круглый стол', 'sections.testimonials.title': 'Отзывы', 'sections.awards.title': 'Награды', 'sections.howTo.title': 'Как участвовать', 'sections.news.title': 'Новости', 'sections.sponsors.title': 'Спонсоры', 'sections.gallery.title': 'Галерея', 'sections.contact.title': 'Контакты', 'placeholder.member': 'Имя участника', 'placeholder.role': 'Должность · Институт', 'placeholder.news': 'Черновая статья.', 'placeholder.logo': 'Логотип-заглушка' }),
  zh: mk({ 'nav.home': '首页', 'nav.committees': '委员会', 'nav.location': '地点', 'nav.program': '日程', 'nav.accommodation': '住宿', 'nav.roundTable': '圆桌论坛', 'nav.testimonials': '评价', 'nav.awards': '奖项', 'nav.howTo': '参与指南', 'nav.news': '新闻', 'nav.sponsors': '赞助商', 'nav.gallery': '画廊', 'nav.contact': '联系', 'hero.ctaRegister': '立即报名', 'hero.ctaLearn': '了解更多', 'countdown.days': '天', 'countdown.hours': '小时', 'countdown.minutes': '分钟', 'countdown.seconds': '秒', 'sections.about.title': '更多介绍', 'sections.committees.title': '委员会', 'sections.location.title': '地点', 'sections.program.title': '日程', 'sections.accommodation.title': '住宿', 'sections.roundTable.title': '圆桌论坛', 'sections.testimonials.title': '评价', 'sections.awards.title': '奖项', 'sections.howTo.title': '参与指南', 'sections.news.title': '新闻', 'sections.sponsors.title': '赞助商', 'sections.gallery.title': '画廊', 'sections.contact.title': '联系', 'placeholder.member': '成员姓名', 'placeholder.role': '职位 · 机构', 'placeholder.news': '文章占位。', 'placeholder.logo': '标志占位' }),
  ja: mk({ 'nav.home': 'ホーム', 'nav.committees': '委員会', 'nav.location': '開催地', 'nav.accommodation': '宿泊', 'nav.roundTable': 'ラウンドテーブル', 'nav.testimonials': '参加者の声', 'nav.awards': '賞', 'nav.howTo': '参加方法', 'nav.news': 'ニュース', 'nav.sponsors': 'スポンサー', 'nav.gallery': 'ギャラリー', 'nav.contact': 'お問い合わせ', 'hero.ctaRegister': '登録する', 'hero.ctaLearn': '詳しく見る', 'countdown.days': '日', 'countdown.hours': '時間', 'countdown.minutes': '分', 'countdown.seconds': '秒', 'sections.about.title': '詳細情報', 'sections.committees.title': '委員会', 'sections.location.title': '開催地', 'sections.program.title': 'プログラム', 'sections.accommodation.title': '宿泊', 'sections.roundTable.title': 'ラウンドテーブル', 'sections.testimonials.title': '参加者の声', 'sections.awards.title': '賞', 'sections.howTo.title': '参加方法', 'sections.news.title': 'ニュース', 'sections.sponsors.title': 'スポンサー', 'sections.gallery.title': 'ギャラリー', 'sections.contact.title': 'お問い合わせ', 'placeholder.member': 'メンバー名', 'placeholder.role': '役職 · 機関', 'placeholder.news': '記事プレースホルダー。', 'placeholder.logo': 'ロゴプレースホルダー' }),
  ar: mk({ 'nav.home': 'الرئيسية', 'nav.committees': 'اللجان', 'nav.location': 'الموقع', 'nav.program': 'البرنامج', 'nav.accommodation': 'الإقامة', 'nav.roundTable': 'الطاولة المستديرة', 'nav.testimonials': 'آراء المشاركين', 'nav.awards': 'الجوائز', 'nav.howTo': 'كيفية المشاركة', 'nav.news': 'الأخبار', 'nav.sponsors': 'الرعاة', 'nav.gallery': 'المعرض', 'nav.contact': 'اتصل بنا', 'hero.ctaRegister': 'سجل الآن', 'hero.ctaLearn': 'اعرف المزيد', 'countdown.days': 'أيام', 'countdown.hours': 'ساعات', 'countdown.minutes': 'دقائق', 'countdown.seconds': 'ثوانٍ', 'sections.about.title': 'نبذة موسعة', 'sections.committees.title': 'اللجان', 'sections.location.title': 'الموقع', 'sections.program.title': 'البرنامج', 'sections.accommodation.title': 'الإقامة', 'sections.roundTable.title': 'الطاولة المستديرة', 'sections.testimonials.title': 'آراء المشاركين', 'sections.awards.title': 'الجوائز', 'sections.howTo.title': 'كيفية المشاركة', 'sections.news.title': 'الأخبار', 'sections.sponsors.title': 'الرعاة', 'sections.gallery.title': 'المعرض', 'sections.contact.title': 'اتصل بنا', 'placeholder.member': 'اسم العضو', 'placeholder.role': 'المنصب · المؤسسة', 'placeholder.news': 'مقال تجريبي.', 'placeholder.logo': 'شعار تجريبي' })
};
